require("toggleterm").setup{
  size = 20,
  open_mapping = [[<C-\>]],
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true, 
  shading_factor = 2,
  start_in_insert = true,
  insert_mappings = true,
  persist_size = true,
  direction = "float",
  close_on_exit = true,
  shell = vim.o.shell,
  terminal_mappings = true,
  float_opts = {
      border = "curved",
      winblend= 0 ,
      highlights = {
          border = "Normal",
          background = "Normal",
      },
  },
  autochdir = false,
  persist_mode = true,
  auto_scroll = true,
}
