source $ZDOTDIR/.zshpath

HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

export RANGER_LOAD_DEFAULT_RC=FALSE


export EDITOR=~/.local/nvim/bin/nvim
export VISUAL=~/.local/nvim/bin/nvim

# plugins
source $ZDOTDIR/plugin/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugin/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
eval "$(starship init zsh)"

source $ZDOTDIR/.zshalias
